### ISSUE TITLE
Wrong highlighting

### ISSUE THREAD

**Issue by Asriel108** [marekaf/docker-lstlisting#3]
One problem for the keywords: 'volumes' and 'networks'. Both of them can be used to

1. (highlevel) to define volumes and networks
2. (lowlevel) to add a volume/network to a service

```
services:
   myservice:
      image: ...
      networks:
         - mynetwork

networks:
   mynetwork:
```

So also the lowlevel words will be colored blue...
Unfortunately it's not easy to define REGEX for keywords in Latex (https://tex.stackexchange.com/questions/159246/can-the-listings-package-highlight-by-regexp)   -_-
